let myDate = new Date()
console.log(myDate.toString())
// console.log(myDate.toLocaleString())
// console.log(myDate.getTimezoneOffset())
console.log(myDate.getHours())
console.log(myDate.toDateString())
